name : Android CI

on :
  push :
    branches : [ "main" ]
  pull_request :
    branches : [ "main" ]

jobs :

  Lint :
    runs-on : ubuntu-latest
    steps :
      
      - name: Checkout the code
        uses : actions/checkout@v3
        
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
          cache : gradle
        
      - name : Run Lint
        run : ./gradlew lintDebug

      - name : Upload HTML test report
        uses : actions/upload-artifact@v2
        with :
          name : index.html
          path : app/build/reports/lint-results-debug.html

  Unit-Testing :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
          cache : gradle

      - name : Grant execute permission for gradlew
        run : chmod +x gradlew

      # Execute unit tests
      - name : Unit Test
        run : ./gradlew testDebugUnitTest


  Coverage-Testing :
    runs-on : ubuntu-latest
    needs: [ Unit-Testing ]
    steps :
      - uses : actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
          cache : gradle

      - name : Grant execute permission for gradlew
        run : chmod +x gradlew

      - name : Coverage
        run : ./gradlew jacocoTestDebugUnitTestReport

      - name : Generate JaCoCo Badge
        uses : cicirello/jacoco-badge-generator@v2
        with :
          generate-branches-badge : true
          badges-directory : .github/badges
          jacoco-csv-file : app/build/jacoco/jacoco.csv

      - name : Log coverage percentage
        run : |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name : Commit and push the badge (if it changed)
        uses : EndBug/add-and-commit@v9
        with :
          default_author : github_actions
          message : 'commit badge'
          add : '*.svg'

      - name : Upload JaCoCo coverage report
        uses : actions/upload-artifact@v2
        with :
          name : jacoco-report
          path : build/jacoco/jacocoHtml/index.html

  Instrumentation-Tests:
    needs : [ Unit-Testing ]
    runs-on : macos-latest
    steps :
      - name : Checkout the code
        uses : actions/checkout@v2

      - name : Run espresso tests
        uses : reactivecircus/android-emulator-runner@v2
        with :
          api-level : 33
          script : ./gradlew connectedCheck

      - name : Upload test report
        uses : actions/upload-artifact@v2
        with :
          name : instrumentation_test_report
          path : app/build/reports/androidTests/connected/

  Mutation-Testing :
    runs-on : ubuntu-latest
    needs: [ Unit-Testing ]
    steps :
      - uses : actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
          cache : gradle

      - name : Grant execute permission for gradlew
        run : chmod +x gradlew

      - name : Run Mutation Tests
        run : ./gradlew pitest

      - name : Upload HTML Mutation report
        uses : actions/upload-artifact@v2
        with :
          name : index.html
          path : app/build/reports/pitest/debug/index.html
          
      - name : Grant execute permission for gradlew
        run : |
          cd ./.github/CICDScripts
          chmod +x gradlew

      - name: Generate Badge
        run: | 
          cd ./.github/CICDScripts
          ./gradlew run

      - name : Commit and push the badge (if it changed)
        uses : EndBug/add-and-commit@v9
        with :
          default_author : github_actions
          message : 'commit mutation badge'
          add : '*.svg'


  Build :
    runs-on : ubuntu-latest

    steps :
      - uses : actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
          cache : gradle

      - name : Grant execute permission for gradlew
        run : chmod +x gradlew

      - name : Build with Gradle
        run : ./gradlew build
        
      
