name : Android CI

on :
  push :
    branches : [ "main" ]
  pull_request :
    branches : [ "main" ]

jobs :

  Lint :
    runs-on : ubuntu-latest
    steps :
      
      - name: Checkout the code
        uses : actions/checkout@v3
        
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
          cache : gradle
        
      - name : Run Lint
        run : ./gradlew lintDebug

      - name : Upload HTML test report
        uses : actions/upload-artifact@v2
        with :
          name : index.html
          path : app/build/reports/lint-results-debug.html
  
  Unit-Testing :
    needs : [ Lint ]
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
         
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
          cache : gradle
          
      - name : Grant execute permission for gradlew
        run : chmod +x gradlew
        
      # Execute unit tests
      - name : Unit Test
        run : ./gradlew testDebugUnitTest


  Coverage-Testing :
    needs : [ Unit-Testing ]
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
         
      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
          cache : gradle
          
      - name : Grant execute permission for gradlew
        run : chmod +x gradlew
        
      - name : Coverage
        run : ./gradlew jacocoTestDebugUnitTestReport
        
      - name : Generate JaCoCo Badge
        uses : cicirello/jacoco-badge-generator@v2
        with :
          generate-branches-badge : true
          badges-directory : .github/badges
          jacoco-csv-file : app/build/jacoco/jacoco.csv

      - name : Log coverage percentage
        run : |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name : Commit and push the badge (if it changed)
        uses : EndBug/add-and-commit@v9
        with :
          default_author : github_actions
          message : 'commit badge'
          add : '*.svg'

      - name : Upload JaCoCo coverage report
        uses : actions/upload-artifact@v2
        with :
          name : jacoco-report
          path : target/site/jacoco/
          
          
  Build :
    needs: [Coverage-Testing]
    runs-on : ubuntu-latest

    steps :
      - uses : actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name : set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
          cache : gradle

      - name : Grant execute permission for gradlew
        run : chmod +x gradlew

      - name : Build with Gradle
        run : ./gradlew build
        
      
