name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Build with Gradle
        run: ./gradlew build

          # Execute unit tests
      - name : Unit Test
        run : ./gradlew testDebugUnitTest

      - name : Coverage
        run : ./gradlew jacocoTestDebugUnitTestReport

      - name : Generate JaCoCo Badge
        uses : cicirello/jacoco-badge-generator@v2
        with :
          generate-branches-badge : true
          jacoco-csv-file : app/build/jacoco/jacoco.csv
